### ISSUE TITLE
Memory leak if we use 'periodicTimeObserver'

### ISSUE THREAD

**Issue by satishVekariya** [pmick/RxAVFoundation#30]
proposed solution

```
public func periodicTimeObserver(interval: CMTime) -> Observable<CMTime> {
        return Observable.create { [unowned base] observer in
            let t = base.addPeriodicTimeObserver(forInterval: interval, queue: nil) { time in
                observer.onNext(time)
            }
            
            return Disposables.create { base.removeTimeObserver(t) }
        }
    }
```

**Comment by pmick** [comment]
Hey, thanks for opening this issue. There isn't a retain cycle on base here. You'll see an almost identical implementation in [RxCocoa for the NotificationCenter extension](https://github.com/ReactiveX/RxSwift/blob/main/RxCocoa/Foundation/NotificationCenter%2BRx.swift).

You'll need to make sure that you're adding your subscription to a dispose bag or explicitly calling dispose on it when you're finished with the subscription. Because this observer never completes or produces an error it will never be released unless you dispose of it.

You can reproduce this with RxCocoa by writing something like `NotificationCenter.default.rx.notification(.AVAssetChapterMetadataGroupsDidChange).subscribe()`, calling this in a view controller you present and dismiss over and over. You'll see that you have a bunch of `SinkDisposer` and `AnonymousDisposable` instances in memory if you aren't explicitly disposing of these subscriptions.
